### PR TITLE
add time_schedule_published to sws term.

### PR DESCRIPTION
**Pull request by btb**
For future terms, queries for curricula or courses will fail unless the time schedule for that quarter has been published, so apps should check the TimeSchedulePublished flag for the term before attempting these queries. 
With this change, apps that allow end-users to query future data can use this flag to filter the available terms.

### CODE REVIEW

**Comment by btb** [comment]
seems ok, but I implemented it that way so as to work identically to time_schedule_construction

**Comment by vegitron** [comment]
Yea, that makes sense, but now that I'm looking at the code that uses it, it's really awkward.  We should probably change time_schedule_construction at some point.  I'm not sure that there's a benefit for either set to be an array, but there do seem to be drawbacks.

**Comment by btb** [comment]
I've now re-implemented time_schedule_published to be a dictionary like time_schedule_construction.

**Comment by vegitron** [comment]
thanks!

**Pull request merged**
