### PR TITLE
Added metadata to Section model

### PR DESCRIPTION
**Pull request by ezturner**

### CODE REVIEW

**Comment by vegitron** [comment]
Are you getting at this metadata to answer specific questions about the section?  If a client application wants to know if this is an SDB course, it would be nice if it didn't need to parse that metadata string.

**Comment by ezturner** [comment]
At Steven's suggestion I had implemented this so that we would have a way to access the:


    "Metadata": "SectionSourceKey=EOS;",

For PCE courses (see [here](https://github.com/uw-it-aca/uw-restclients/blob/develop/restclients/resources/sws/file/student/v5/course/2013_spring_ESS_107/A.json))

**Comment by vegitron** [comment]
Right, but there's the question of why - you say you're interested in it when it says EOS, rather than my example of SDB.  What code going to parse that string to determine if it's an EOS course or an SDB course, and why should it be that code?

**Comment by ezturner** [comment]
At the moment there's no specific piece of code that will be consuming this functionality. The initial suggestion was to simply make this available for client apps to utilize but I can see what you're saying about refraining from making model modifications that will consume additional resources without a clear use case/justification.

**Pull request closed without merging**
